on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.meetingmindsonline.com
        username: krishna@abstracts.meetingmindsonline.com
        password: $2kf5rEcW?[w
        remote-dir: public_html/abstracts.meetingmindsonline.com/
        log-level: standard 
        

    - name: Verify Deployment
      run: echo "Deployment to FTP server completed!"