name: FTP Deploy

on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name:  🚚 Get latest code
      uses: actions/checkout@v3

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.meetingmindsonline.com
        username: krishna@abstracts.meetingmindsonline.com
        password: $2kf5rEcW?[w
        remote-dir: 'public_html/abstracts.meetingmindsonline.com/'
        log-level: standard 
        

    - name: Verify Deployment
      run: echo "Deployment to FTP server completed!"